// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async computerInfo() : Promise<Computer> {
    return await TAURI_INVOKE("computer_info");
},
async displayInfo() : Promise<Display> {
    return await TAURI_INVOKE("display_info");
},
async audioInfo() : Promise<Audio> {
    return await TAURI_INVOKE("audio_info");
},
/**
 * Install packages via pacman (uses pkexec for root)
 */
async installPackages(packages: string[]) : Promise<BackendResult> {
    return await TAURI_INVOKE("install_packages", { packages });
},
/**
 * Remove packages via pacman (uses pkexec for root).
 * Tries each package individually so one dependency failure doesn't block the rest.
 * When `force` is true, uses `-Rdd` (skip dependency checks) instead of `-R`.
 */
async removePackages(packages: string[], force: boolean) : Promise<BackendResult> {
    return await TAURI_INVOKE("remove_packages", { packages, force });
},
/**
 * Update pacman database (uses pkexec for root)
 */
async updateDb() : Promise<BackendResult> {
    return await TAURI_INVOKE("update_db");
},
async checkPackageInstalled(packageName: string) : Promise<boolean> {
    return await TAURI_INVOKE("check_package_installed", { packageName });
},
/**
 * Install a full profile.
 * 
 * This reads the profile data from the frontend (which already parsed the TOML),
 * then calls pacman install + systemctl enable as needed.
 */
async installProfile(profileName: string, packages: string[], services: string[]) : Promise<BackendResult> {
    return await TAURI_INVOKE("install_profile", { profileName, packages, services });
},
/**
 * Uninstall a profile's packages
 */
async uninstallProfile(profileName: string, packages: string[], services: string[]) : Promise<BackendResult> {
    return await TAURI_INVOKE("uninstall_profile", { profileName, packages, services });
},
/**
 * Enable a service via systemctl (uses pkexec for root)
 */
async enableService(serviceName: string, startNow: boolean) : Promise<BackendResult> {
    return await TAURI_INVOKE("enable_service", { serviceName, startNow });
},
/**
 * Disable a service via systemctl (uses pkexec for root)
 */
async disableService(serviceName: string, stopNow: boolean) : Promise<BackendResult> {
    return await TAURI_INVOKE("disable_service", { serviceName, stopNow });
},
/**
 * Load all profiles from the profiles directory using TomlLoader from libs
 */
async listProfiles() : Promise<ProfileInfo[]> {
    return await TAURI_INVOKE("list_profiles");
},
/**
 * Get a single profile by ID
 */
async getProfile(profileId: string) : Promise<ProfileInfo | null> {
    return await TAURI_INVOKE("get_profile", { profileId });
},
async initConfigurationFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_configuration_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkConfigurationFile() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_configuration_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindow() : Promise<void> {
    await TAURI_INVOKE("show_main_window");
},
async getGrubThemes() : Promise<ThemeManifest[]> {
    return await TAURI_INVOKE("get_grub_themes");
},
async setGrubTheme(themeName: string) : Promise<ApiResultVoid> {
    return await TAURI_INVOKE("set_grub_theme", { themeName });
},
async getCacheSize() : Promise<Result<bigint, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanCache() : Promise<Result<LocalCommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshMirror(country: string | null) : Promise<Result<LocalCommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_mirror", { country }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchDns(provider: DnsProvider) : Promise<Result<LocalCommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_dns", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCpuProfile(profile: CpuProfile) : Promise<Result<LocalCommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cpu_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSwapMode(mode: SwapMode) : Promise<Result<LocalCommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_swap_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSwapEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_swap_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentDnsProvider() : Promise<Result<DnsProvider | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_dns_provider") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCpuGovernorState() : Promise<Result<CpuProfile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cpu_governor_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ApiResultVoid = { success: boolean; error?: string | null; code?: string | null }
export type Audio = { devices: string[]; errors: string[] }
export type BackendResult = { success: boolean; stdout: string; stderr: string; exit_code: number }
export type Computer = { processor: string; memory: bigint; operating_system: string; kernel_version: string; username: string[]; errors: string[] }
export type CpuProfile = "powersave" | "performance" | "ondemand"
export type Display = { monitor_name: string[]; graphic_cards: string[]; display_protocol: string; display_windows_manager: string; errors: string[] }
export type DnsProvider = "cloudflare" | "google" | "quad9" | "opendns" | "adguard"
export type LocalCommandOutput = { exit_code: number; stdout: string; stderr: string; success: boolean }
/**
 * Profile metadata exposed to the frontend via Tauri commands.
 * This is a DTO (Data Transfer Object) that wraps the libs' domain model
 * with `specta::Type` for TypeScript binding generation.
 */
export type ProfileInfo = { id: string; name: string; description: string; version: string; author: string; category: string; packages_install: string[]; packages_aur: string[]; packages_remove: string[]; services_enable: string[]; services_disable: string[]; package_count: number }
export type Step = { type: "copy_dir"; from: string; to: string } | { type: "copy_file"; from: string; to: string } | { type: "set_grub_var"; key: string; value: string } | { type: "replace_in_file"; file: string; search: string; replace: string }
export type SwapMode = "enable" | "disable"
export type ThemeManifest = { name: string; version: string; github_url: string | null; preview_image: string | null; description: string | null; author: string | null; name_concat: string | null; steps: Step[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
