/**
 * install.svelte.ts — Global persistent install state store.
 *
 * Using Svelte 5 $state in a module-level singleton so the state
 * survives navigation / component unmount / remount cycles.
 *
 * State is NEVER reset on component destroy — only explicit API calls
 * can clear it.
 */

import { installStateStore } from './installState.svelte';

// ─── Types ────────────────────────────────────────────────────────────────────

export type InstallPhase =
	| 'idle'
	| 'queued'
	| 'installing'
	| 'success'
	| 'error'
	| 'cancelled';

export type InstallStep =
	| 'idle'
	| 'db-update'
	| 'installing'
	| 'services'
	| 'done';

export type LogEntry = {
	line: string;
	stream: 'stdout' | 'stderr' | 'system';
	ts: number;
};

export type InstallTask = {
	/** Unique task id generated by frontend */
	id: string;
	/** Human-readable profile / package group name */
	label: string;
	/** Packages being installed */
	packages: string[];
	/** Services to enable after install */
	services: string[];
	/** Profile id (may be empty for ad-hoc installs) */
	profileId: string;
	/** Current phase */
	phase: InstallPhase;
	/** Current step within phase */
	step: InstallStep;
	/** Progress 0-100 */
	progress: number;
	/** Structured log entries */
	logs: LogEntry[];
	/** Short summary shown in toasts / overlay */
	message: string;
	/** Timestamp when task started (ms epoch) */
	startedAt: number | null;
	/** Timestamp when task finished (ms epoch) */
	finishedAt: number | null;
};

export type UninstallTask = {
	id: string;
	label: string;
	packages: string[];
	services: string[];
	profileId: string;
	phase: 'idle' | 'uninstalling' | 'success' | 'error';
	logs: LogEntry[];
	message: string;
	hasDependencyError: boolean;
	startedAt: number | null;
	finishedAt: number | null;
};

// ─── Singleton state ──────────────────────────────────────────────────────────

function createInstallStore() {
	// Active install task (one at a time)
	let activeInstall = $state<InstallTask | null>(null);
	// Active uninstall task (one at a time)
	let activeUninstall = $state<UninstallTask | null>(null);

	// History: completed / failed tasks (last 20)
	let history = $state<InstallTask[]>([]);

	// Per-profile install state cache (for card UI)
	let profileStates = $state<Record<string, InstallPhase>>({});

	// ── Helpers ──────────────────────────────────────────────────────────────

	function pushLog(
		task: InstallTask | UninstallTask,
		line: string,
		stream: 'stdout' | 'stderr' | 'system' = 'system'
	) {
		// Throttle: keep at most 500 log lines
		if (task.logs.length >= 500) task.logs.shift();
		task.logs.push({ line, stream, ts: Date.now() });
	}

	// ── Install API ───────────────────────────────────────────────────────────

	function startInstall(opts: {
		id: string;
		label: string;
		packages: string[];
		services: string[];
		profileId: string;
	}): InstallTask {
		const task: InstallTask = {
			...opts,
			phase: 'installing',
			step: 'idle',
			progress: 0,
			logs: [
				{
					line: `[${new Date().toLocaleTimeString()}] Starting install: ${opts.label}`,
					stream: 'system',
					ts: Date.now()
				}
			],
			message: `Installing ${opts.packages.length} package(s)…`,
			startedAt: Date.now(),
			finishedAt: null
		};
		activeInstall = task;
		profileStates[opts.profileId] = 'installing';

		// Also register in individual package state store
		installStateStore.registerInstall(opts.id, opts.label, opts.packages, opts.services);

		return task;
	}

	function appendInstallLog(
		line: string,
		stream: 'stdout' | 'stderr' | 'system' = 'system'
	) {
		if (!activeInstall) return;
		pushLog(activeInstall, line, stream);
		// Also update individual package state store
		installStateStore.appendLog(activeInstall.id, line, stream);
	}

	function updateInstallProgress(step: InstallStep, percent: number) {
		if (!activeInstall) return;
		activeInstall.step = step;
		activeInstall.progress = Math.min(100, Math.max(0, percent));
		// Update message based on step
		const stepLabels: Record<InstallStep, string> = {
			idle: 'Preparing…',
			'db-update': 'Updating package database…',
			installing: `Installing ${activeInstall.packages.length} package(s)…`,
			services: 'Enabling services…',
			done: 'Finishing up…'
		};
		activeInstall.message = stepLabels[step] ?? 'Installing…';

		// Also update individual package state store
		installStateStore.updateProgress(activeInstall.id, step, percent);
	}

	function finishInstall(success: boolean, message: string) {
		if (!activeInstall) return;
		activeInstall.phase = success ? 'success' : 'error';
		activeInstall.progress = success ? 100 : activeInstall.progress;
		activeInstall.step = success ? 'done' : activeInstall.step;
		activeInstall.message = message;
		activeInstall.finishedAt = Date.now();
		profileStates[activeInstall.profileId] = success ? 'success' : 'error';

		// Archive to history
		history = [{ ...activeInstall }, ...history].slice(0, 20);

		// Also update individual package state store
		installStateStore.finishInstall(activeInstall.id, success, message);

		// Keep task visible for 8 s, then clear
		const taskId = activeInstall.id;
		setTimeout(() => {
			if (activeInstall?.id === taskId && activeInstall.phase !== 'installing') {
				activeInstall = null;
			}
		}, 8000);
	}

	function cancelInstall() {
		if (!activeInstall) return;
		activeInstall.phase = 'cancelled';
		activeInstall.message = 'Install cancelled.';
		activeInstall.finishedAt = Date.now();
		profileStates[activeInstall.profileId] = 'idle';
		history = [{ ...activeInstall }, ...history].slice(0, 20);

		// Also update individual package state store
		installStateStore.cancelInstall(activeInstall.id);

		activeInstall = null;
	}

	function resetInstall(profileId?: string) {
		if (activeInstall && (!profileId || activeInstall.profileId === profileId)) {
			// Clear in individual package store too
			installStateStore.cancelInstall(activeInstall.id);
			activeInstall = null;
		}
		if (profileId) {
			profileStates[profileId] = 'idle';
		}
	}

	function restoreActiveInstall(task: InstallTask) {
		activeInstall = task;
		profileStates[task.profileId] = task.phase;
	}

	// ── Uninstall API ─────────────────────────────────────────────────────────

	function startUninstall(opts: {
		id: string;
		label: string;
		packages: string[];
		services: string[];
		profileId: string;
	}): UninstallTask {
		const task: UninstallTask = {
			...opts,
			phase: 'uninstalling',
			logs: [
				{
					line: `[${new Date().toLocaleTimeString()}] Starting removal: ${opts.label}`,
					stream: 'system',
					ts: Date.now()
				}
			],
			message: `Removing ${opts.packages.length} package(s)…`,
			hasDependencyError: false,
			startedAt: Date.now(),
			finishedAt: null
		};
		activeUninstall = task;
		return task;
	}

	function appendUninstallLog(
		line: string,
		stream: 'stdout' | 'stderr' | 'system' = 'system'
	) {
		if (!activeUninstall) return;
		pushLog(activeUninstall, line, stream);
	}

	function finishUninstall(
		success: boolean,
		message: string,
		hasDependencyError = false
	) {
		if (!activeUninstall) return;
		activeUninstall.phase = success ? 'success' : 'error';
		activeUninstall.message = message;
		activeUninstall.hasDependencyError = hasDependencyError;
		activeUninstall.finishedAt = Date.now();

		if (success) {
			setTimeout(() => {
				if (activeUninstall?.phase === 'success') activeUninstall = null;
			}, 3000);
		}
	}

	function resetUninstall() {
		activeUninstall = null;
	}

	// ── Derived ───────────────────────────────────────────────────────────────

	return {
		// Reads
		get activeInstall() {
			return activeInstall;
		},
		get activeUninstall() {
			return activeUninstall;
		},
		get history() {
			return history;
		},
		get profileStates() {
			return profileStates;
		},

		/** True when any install/uninstall is in progress */
		get isBusy() {
			return (
				activeInstall?.phase === 'installing' ||
				activeUninstall?.phase === 'uninstalling'
			);
		},

		getProfilePhase(profileId: string): InstallPhase {
			return profileStates[profileId] ?? 'idle';
		},

		// Install mutations
		startInstall,
		appendInstallLog,
		updateInstallProgress,
		finishInstall,
		cancelInstall,
		resetInstall,
		restoreActiveInstall,

		// Uninstall mutations
		startUninstall,
		appendUninstallLog,
		finishUninstall,
		resetUninstall
	};
}

export const installStore = createInstallStore();
