export const validDevicons = new Set(['aarch64',
    'adonisjs',
    'aerospike',
    'aframe',
    'aftereffects',
    'akka',
    'algolia',
    'almalinux',
    'alpinejs',
    'amazonwebservices',
    'anaconda',
    'android',
    'androidstudio',
    'angular',
    'angularjs',
    'angularmaterial',
    'ansible',
    'ansys',
    'antdesign',
    'apache',
    'apacheairflow',
    'apachekafka',
    'apachespark',
    'apex',
    'apl',
    'apollographql',
    'appcelerator',
    'apple',
    'appwrite',
    'archlinux',
    'arduino',
    'argocd',
    'artixlinux',
    'astro',
    'atom',
    'awk',
    'axios',
    'azure',
    'azuredevops',
    'azuresqldatabase',
    'babel',
    'babylonjs',
    'backbonejs',
    'ballerina',
    'bamboo',
    'bash',
    'bazel',
    'beats',
    'behance',
    'bevyengine',
    'biome',
    'bitbucket',
    'blazor',
    'blender',
    'bootstrap',
    'bower',
    'browserstack',
    'bulma',
    'bun',
    'c',
    'cairo',
    'cakephp',
    'canva',
    'capacitor',
    'carbon',
    'cassandra',
    'centos',
    'ceylon',
    'chakraui',
    'chartjs',
    'chrome',
    'circleci',
    'clarity',
    'clickhouse',
    'clion',
    'clojure',
    'clojurescript',
    'cloudflare',
    'cloudflareworkers',
    'cloudrun',
    'cmake',
    'cobol',
    'codeac',
    'codecov',
    'codeigniter',
    'codepen',
    'coffeescript',
    'composer',
    'confluence',
    'consul',
    'contao',
    'corejs',
    'cosmosdb',
    'couchbase',
    'couchdb',
    'cpanel',
    'cplusplus',
    'crystal',
    'csharp',
    'css3',
    'cucumber',
    'cypressio',
    'd3js',
    'dart',
    'datadog',
    'datagrip',
    'dataspell',
    'datatables',
    'dbeaver',
    'debian',
    'delphi',
    'denojs',
    'detaspace',
    'devicon',
    'digitalocean',
    'discloud',
    'discordjs',
    'django',
    'djangorest',
    'docker',
    'doctrine',
    'dot-net',
    'dotnetcore',
    'dovecot',
    'dreamweaver',
    'dropwizard',
    'drupal',
    'duckdb',
    'dyalog',
    'dynamodb',
    'dynatrace',
    'eclipse',
    'ecto',
    'elasticsearch',
    'electron',
    'eleventy',
    'elixir',
    'elm',
    'emacs',
    'embeddedc',
    'ember',
    'entityframeworkcore',
    'envoy',
    'erlang',
    'eslint',
    'expo',
    'express',
    'facebook',
    'fastapi',
    'fastify',
    'faunadb',
    'feathersjs',
    'fedora',
    'fiber',
    'figma',
    'filamentphp',
    'filezilla',
    'firebase',
    'firebird',
    'firefox',
    'flask',
    'flutter',
    'forgejo',
    'fortran',
    'foundation',
    'framermotion',
    'framework7',
    'fsharp',
    'fusion',
    'gardener',
    'gatling',
    'gatsby',
    'gazebo',
    'gcc',
    'gentoo',
    'ghost',
    'gimp',
    'git',
    'gitbook',
    'github',
    'githubactions',
    'githubcodespaces',
    'gitkraken',
    'gitlab',
    'gitpod',
    'gitter',
    'gleam',
    'glitch',
    'go',
    'godot',
    'goland',
    'google',
    'googlecloud',
    'googlecolab',
    'gradle',
    'grafana',
    'grails',
    'graphql',
    'groovy',
    'grpc',
    'grunt',
    'gulp',
    'hadoop',
    'handlebars',
    'harbor',
    'hardhat',
    'harvester',
    'haskell',
    'haxe',
    'helm',
    'heroku',
    'hibernate',
    'homebrew',
    'hoppscotch',
    'html5',
    'htmx',
    'hugo',
    'hyperv',
    'ie10',
    'ifttt',
    'illustrator',
    'inertiajs',
    'influxdb',
    'inkscape',
    'insomnia',
    'intellij',
    'ionic',
    'jaegertracing',
    'jamstack',
    'jasmine',
    'java',
    'javascript',
    'jeet',
    'jekyll',
    'jenkins',
    'jest',
    'jetbrains',
    'jetpackcompose',
    'jhipster',
    'jira',
    'jiraalign',
    'jquery',
    'json',
    'jule',
    'julia',
    'junit',
    'jupyter',
    'k3os',
    'k3s',
    'k6',
    'kaggle',
    'kaldi',
    'kalilinux',
    'karatelabs',
    'karma',
    'kdeneon',
    'keras',
    'kibana',
    'knexjs',
    'knockout',
    'kotlin',
    'krakenjs',
    'ktor',
    'kubeflow',
    'kubernetes',
    'labview',
    'laminas',
    'laravel',
    'laraveljetstream',
    'latex',
    'leetcode',
    'less',
    'libgdx',
    'linkedin',
    'linux',
    'linuxmint',
    'liquibase',
    'livewire',
    'llvm',
    'lodash',
    'logstash',
    'love2d',
    'lua',
    'lumen',
    'magento',
    'mapbox',
    'mariadb',
    'markdown',
    'materializecss',
    'materialui',
    'matlab',
    'matplotlib',
    'mattermost',
    'maven',
    'maya',
    'memcached',
    'mercurial',
    'meteor',
    'microsoftsqlserver',
    'minitab',
    'mithril',
    'mobx',
    'mocha',
    'modx',
    'moleculer',
    'mongodb',
    'mongoose',
    'monogame',
    'moodle',
    'msdos',
    'mysql',
    'nano',
    'nats',
    'neo4j',
    'neovim',
    'nestjs',
    'netbeans',
    'netbox',
    'netlify',
    'networkx',
    'newrelic',
    'nextjs',
    'nginx',
    'ngrok',
    'ngrx',
    'nhibernate',
    'nim',
    'nimble',
    'nixos',
    'nodejs',
    'nodemon',
    'nodered',
    'nodewebkit',
    'nomad',
    'norg',
    'notion',
    'npm',
    'npss',
    'nuget',
    'numpy',
    'nuxt',
    'nuxtjs',
    'oauth',
    'objectivec',
    'ocaml',
    'ohmyzsh',
    'okta',
    'openal',
    'openapi',
    'opencl',
    'opencv',
    'opengl',
    'openstack',
    'opensuse',
    'opentelemetry',
    'opera',
    'oracle',
    'ory',
    'p5js',
    'packer',
    'pandas',
    'passport',
    'perl',
    'pfsense',
    'phalcon',
    'phoenix',
    'photonengine',
    'photoshop',
    'php',
    'phpstorm',
    'pixijs',
    'playwright',
    'plotly',
    'pm2',
    'pnpm',
    'podman',
    'poetry',
    'polygon',
    'portainer',
    'postcss',
    'postgresql',
    'postman',
    'powershell',
    'premierepro',
    'primeng',
    'prisma',
    'processing',
    'processwire',
    'prolog',
    'prometheus',
    'protractor',
    'proxmox',
    'pug',
    'pulsar',
    'pulumi',
    'puppeteer',
    'purescript',
    'putty',
    'pycharm',
    'pypi',
    'pyscript',
    'pytest',
    'python',
    'pytorch',
    'qodana',
    'qt',
    'qtest',
    'quarkus',
    'quasar',
    'qwik',
    'r',
    'rabbitmq',
    'racket',
    'radstudio',
    'rails',
    'railway',
    'rancher',
    'raspberrypi',
    'reach',
    'react',
    'reactbootstrap',
    'reactnative',
    'reactnavigation',
    'reactrouter',
    'readthedocs',
    'realm',
    'rect',
    'redhat',
    'redis',
    'redux',
    'reflex',
    'remix',
    'renpy',
    'replit',
    'rexx',
    'rider',
    'rocksdb',
    'rockylinux',
    'rollup',
    'ros',
    'rspec',
    'rstudio',
    'ruby',
    'rubymine',
    'rust',
    'rxjs',
    'safari',
    'salesforce',
    'sanity',
    'sass',
    'scala',
    'scalingo',
    'scikitlearn',
    'sdl',
    'selenium',
    'sema',
    'sentry',
    'sequelize',
    'shopware',
    'shotgrid',
    'sketch',
    'slack',
    'socketio',
    'solidity',
    'solidjs',
    'sonarqube',
    'sourceengine',
    'sourcetree',
    'spack',
    'spicedb',
    'splunk',
    'spring',
    'spss',
    'spyder',
    'sqlalchemy',
    'sqldeveloper',
    'sqlite',
    'ssh',
    'stackblitz',
    'stackoverflow',
    'stata',
    'stenciljs',
    'storybook',
    'streamlit',
    'styledcomponents',
    'stylus',
    'subversion',
    'sulu',
    'supabase',
    'surrealdb',
    'svelte',
    'svgo',
    'swagger',
    'swift',
    'swiper',
    'symfony',
    'tailwindcss',
    'talos',
    'tauri',
    'teleport',
    'tensorflow',
    'terraform',
    'terramate',
    'tex',
    'thealgorithms',
    'threedsmax',
    'threejs',
    'thymeleaf',
    'titaniumsdk',
    'tmux',
    'tomcat',
    'tortoisegit',
    'towergit',
    'traefikmesh',
    'traefikproxy',
    'travis',
    'trello',
    'trpc',
    'turbo',
    'twilio',
    'twitter',
    'typescript',
    'typo3',
    'ubuntu',
    'unifiedmodelinglanguage',
    'unity',
    'unix',
    'unrealengine',
    'uwsgi',
    'v8',
    'vaadin',
    'vagrant',
    'vala',
    'vault',
    'veevalidate',
    'vercel',
    'vertx',
    'vim',
    'visualbasic',
    'visualstudio',
    'vite',
    'vitejs',
    'vitess',
    'vitest',
    'vscode',
    'vscodium',
    'vsphere',
    'vuejs',
    'vuestorefront',
    'vuetify',
    'vulkan',
    'vyper',
    'waku',
    'wasm',
    'web3js',
    'webflow',
    'webgpu',
    'weblate',
    'webpack',
    'webstorm',
    'windows11',
    'windows8',
    'wolfram',
    'woocommerce',
    'wordpress',
    'xamarin',
    'xcode',
    'xd',
    'xml',
    'yaml',
    'yarn',
    'yii',
    'yugabytedb',
    'yunohost',
    'zend',
    'zig',
    'zsh',
    'zustand'
]);

export function getDeviconClass(pkg: string): string | null {
    if (!pkg) return null;
    const normalized = pkg.toLowerCase();

    // Exact match
    if (validDevicons.has(normalized)) return `devicon-${normalized}-plain colored`;

    // Common package name to devicon name mappings for linux packages
    const mappings: Record<string, string> = {
        'nodejs': 'nodejs',
        'node': 'nodejs',
        'postgres': 'postgresql',
        'postgresql': 'postgresql',
        'golang': 'go',
        'rustc': 'rust',
        'cargo': 'rust',
        'python3': 'python',
        'ruby': 'ruby',
        'visual-studio-code': 'vscode',
        'vscode': 'vscode',
        'docker-compose': 'docker',
        'mariadb-server': 'mariadb',
        'mysql-server': 'mysql',
        'beekeeper-studio-bin': 'mysql',
        'linux-firmware': 'linux',
        'android-tools': 'android',
        'jupyterlab': 'jupyter',
        'virtualbox': 'virtualbox',
        'onlyoffice-bin': 'linux',
        'clang': 'c',
        'mariadb-clients': 'mariadb',
        'k9s': 'kubernetes',
        'aws-cli': 'amazonwebservices',
        'bun-bin': 'bun',
        'rust-analyzer': 'rust',
        'insomnia-bin': 'insomnia',
        'base-devel': 'linux',
        'brave-bin': 'chrome',
        'android-studio': 'androidstudio',
        'obs-studio': 'linux',
        'gopls': 'go',
        'kubectl': 'kubernetes',
        'azure-cli': 'azure',
        'jdk-openjdk': 'java',
        'arduino-ide-bin': 'arduino',
        'code': 'vscode',
        'jupyter-notebook': 'jupyter',
        'telegram-desktop': 'linux',
        'python-matplotlib': 'matplotlib',
        'libreoffice-fresh': 'linux',
        'python-pip': 'python',
        'arduino-cli': 'arduino',
        'postman-bin': 'postman',
        'lazydocker-bin': 'docker',
        'phpmyadmin': 'php',
        'google-cloud-cli': 'googlecloud',
        'python-tensorflow': 'tensorflow',
        'php-fpm': 'php',
        'php-sqlite': 'php',
        'virtualbox-host-modules-arch': 'virtualbox',
        'intellij-idea-community-edition': 'intellij',
        'minikube': 'kubernetes',
        'php-apache': 'php',
        'python-seaborn': 'python',
        'buildah': 'podman',
        'visual-studio-code-bin': 'vscode',
        'oh-my-zsh-git': 'ohmyzsh',
        'chromium': 'chrome',
        'python-numpy': 'numpy',
        'discord': 'discordjs',
        'python-pandas': 'pandas',
        'python-pytorch': 'pytorch',
        'vlc': 'linux',
        'rustup': 'rust',
        'php-gd': 'php',
        'python-scipy': 'python',
        'openssh': 'ssh',
        'ipython': 'python',
        'make': 'c',
        'gdb': 'c',
        'valgrind': 'c',
        'xdebug': 'php'
    };

    if (mappings[normalized]) return `devicon-${mappings[normalized]}-plain colored`;

    // Strip numbers for basic heuristic (e.g. clang-14 -> clang, python310 -> python)
    const stripped = normalized.replace(/[^a-z]/g, '');
    if (validDevicons.has(stripped)) return `devicon-${stripped}-plain colored`;

    return null;
}
