// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure CPU' command

use serde::{Deserialize, Serialize};

pub type CpuFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Result,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub cpu: String,
    pub vendor: String,
    pub packages: i64,
    pub cores: Cores,
    pub frequency: Frequency,
    pub core_types: Vec<Option<serde_json::Value>>,
    pub temperature: Option<serde_json::Value>,
    pub march: String,
    pub numa_nodes: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Cores {
    pub physical: i64,
    pub logical: i64,
    pub online: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Frequency {
    pub base: i64,
    pub max: i64,
}
