// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Display' command


use serde::{Serialize, Deserialize};

pub type DisplayFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    welcome_type: String,
    result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    id: i64,
    name: String,
    primary: bool,
    output: Output,
    scaled: Physical,
    preferred: Output,
    physical: Physical,
    rotation: i64,
    bit_depth: i64,
    hdr_status: String,
    #[serde(rename = "type")]
    result_type: String,
    manufacture_date: ManufactureDate,
    serial: Option<serde_json::Value>,
    platform_api: String,
}

#[derive(Serialize, Deserialize)]
pub struct ManufactureDate {
    year: i64,
    week: i64,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    width: i64,
    height: i64,
    refresh_rate: i64,
    drr_status: Option<serde_json::Value>,
}

#[derive(Serialize, Deserialize)]
pub struct Physical {
    width: i64,
    height: i64,
}
