// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Display' command

use serde::{Deserialize, Serialize};

pub type DisplayFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub id: i64,
    pub name: String,
    pub primary: bool,
    pub output: Output,
    pub scaled: Physical,
    pub preferred: Output,
    pub physical: Physical,
    pub rotation: i64,
    pub bit_depth: i64,
    pub hdr_status: String,
    #[serde(rename = "type")]
    pub result_type: String,
    pub manufacture_date: ManufactureDate,
    pub serial: Option<serde_json::Value>,
    pub platform_api: String,
}

#[derive(Serialize, Deserialize)]
pub struct ManufactureDate {
    pub year: i64,
    pub week: i64,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub width: i64,
    pub height: i64,
    pub refresh_rate: f64,
    pub drr_status: Option<serde_json::Value>,
}

#[derive(Serialize, Deserialize)]
pub struct Physical {
    pub width: i64,
    pub height: i64,
}
