// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure GPU' command

use serde::{Deserialize, Serialize};

pub type GPUFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub index: Option<serde_json::Value>,
    pub core_count: Option<serde_json::Value>,
    pub core_usage: Option<serde_json::Value>,
    pub memory: Memory,
    pub driver: String,
    pub name: String,
    pub temperature: Option<serde_json::Value>,
    #[serde(rename = "type")]
    pub result_type: Option<String>,
    pub vendor: Option<String>,
    pub platform_api: Option<String>,
    pub frequency: Option<serde_json::Value>,
    pub device_id: Option<i64>,
}

#[derive(Serialize, Deserialize)]
pub struct Memory {
    pub dedicated: Dedicated,
    pub shared: Dedicated,
    #[serde(rename = "type")]
    pub memory_type: Option<serde_json::Value>,
}

#[derive(Serialize, Deserialize)]
pub struct Dedicated {
    pub total: Option<serde_json::Value>,
    pub used: Option<serde_json::Value>,
}
