// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure GPU' command

use serde::{Serialize, Deserialize};

pub type GPUFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    welcome_type: String,
    result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    index: Option<serde_json::Value>,
    core_count: Option<serde_json::Value>,
    core_usage: Option<serde_json::Value>,
    memory: Memory,
    driver: String,
    name: String,
    temperature: Option<serde_json::Value>,
    #[serde(rename = "type")]
    result_type: String,
    vendor: String,
    platform_api: String,
    frequency: Option<serde_json::Value>,
    device_id: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Memory {
    dedicated: Dedicated,
    shared: Dedicated,
    #[serde(rename = "type")]
    memory_type: Option<serde_json::Value>,
}

#[derive(Serialize, Deserialize)]
pub struct Dedicated {
    total: Option<serde_json::Value>,
    used: Option<serde_json::Value>,
}
