// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Kernel' command

use serde::{Deserialize, Serialize};

pub type KernelFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Result,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub architecture: String,
    pub name: String,
    pub release: String,
    pub version: String,
    pub page_size: i64,
}
