// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Memory' command

use serde::{Deserialize, Serialize};

pub type MemoryFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Result,
}

#[derive(Serialize, Deserialize)]
pub struct Result {
    pub total: i64,
    pub used: i64,
}
