// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure OS' command

use serde::{Deserialize, Serialize};

pub type OSFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Result,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    #[serde(rename = "buildID")]
    pub build_id: String,
    pub codename: String,
    pub id: String,
    pub id_like: String,
    pub name: String,
    pub pretty_name: String,
    pub variant: String,
    #[serde(rename = "variantID")]
    pub variant_id: String,
    pub version: String,
    #[serde(rename = "versionID")]
    pub version_id: String,
}
