// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Sound' command

use serde::{Deserialize, Serialize};

pub type SoundFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub active: bool,
    pub main: bool,
    pub volume: i64,
    pub name: String,
    pub identifier: String,
    pub platform_api: String,
}
