// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure Users' command

use serde::{Deserialize, Serialize};

pub type UsersFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Vec<Result>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub name: String,
    pub host_name: String,
    pub session_name: String,
    pub client_ip: String,
    pub login_time: String,
}
