// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure WM' command

use serde::{Deserialize, Serialize};

pub type WMFastfetch = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    pub welcome_type: String,
    pub result: Result,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    pub process_name: String,
    pub pretty_name: String,
    pub protocol_name: String,
    pub plugin_name: String,
    pub version: String,
}
