// This code is generated by: https://app.quicktype.io/
// The type came from 'fastfetch --format json --structure WM' command


use serde::{Serialize, Deserialize};

pub type Welcome = Vec<WelcomeElement>;

#[derive(Serialize, Deserialize)]
pub struct WelcomeElement {
    #[serde(rename = "type")]
    welcome_type: String,
    result: Result,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    process_name: String,
    pretty_name: String,
    protocol_name: String,
    plugin_name: String,
    version: String,
}
