[meta]
name = "AI Pack"
description = "Tools untuk pengembangan AI dan integrasi."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"

[packages]
install = [
    "python",
    "python-pip",
    "jupyter-notebook"
]

aur = [
    "ollama-bin",
    "python-pytorch",
    "python-tensorflow"
]

[services]
enable = ["ollama"]
