[meta]
name = "Android Developer Pack"
description = "Paket pengembangan aplikasi Android."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"

[packages]
install = [
    "android-tools",
    "jdk-openjdk"
]

aur = [
    "android-studio"
]

[services]
enable = []
