[meta]
name = "C++ dan Java Pack"
description = "Paket pengembangan C dan C++."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"
icon = "cpp_java.svg"

[packages]
install = [ "gcc", "clang", "make", "cmake", "gdb", "valgrind", "codeblocks", "jdk-openjdk", "maven", "gradle", "ant",]
aur = [ "intellij-idea-community-edition",]

[services]
enable = []
