[meta]
name = "Gaming Pack"
description = "Paket gaming Linux untuk performa dan kompabilitas terbaik."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "games"

[packages]
install = [
    "steam",
    "gamemode",
    "mangohud",
    "lutris",
    "wine",
    "winetricks"
]

aur = [
    "heroic-games-launcher-bin"
]

[services]
enable = []
