[meta]
name = "Kubernetes Pack"
description = "Paket pengembangan Kubernetes."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "server"

[packages]
install = [
    "kubectl",
    "minikube",
    "helm",
    "k9s"
]

aur = []

[services]
enable = []
