[meta]
name = "LAMPP Compatibility"
description = "Compatibility package for XAMPP/LAMPP users."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"

[packages]
install = [
    "apache",
    "mariadb",
    "php",
    "php-apache",
    "perl",
    "phpmyadmin"
]

aur = []

[services]
enable = ["httpd", "mariadb"]
