[meta]
name = "Laptop Optimization Pack"
description = "Tools untuk optimasi baterai dan performa laptop."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "system"

[packages]
install = [
    "tlp",
    "powertop",
    "brightnessctl"
]

aur = []

[services]
enable = ["tlp"]
