[meta]
name = "Network Pack"
description = "Network monitoring and analysis tools."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "security"

[packages]
install = [
    "wireshark-qt",
    "nmap",
    "net-tools",
    "traceroute",
    "tcpdump",
    "remmina"
]

aur = []

[services]
enable = []
