[meta]
name = "Student Setup"
description = "Complete setup for students (Office, Internet, Multimedia)."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "education"

[packages]
install = [ "evince", "ffmpeg", "firefox", "flameshot", "fonts-noto", "gst-plugins-bad", "gst-plugins-good", "gst-plugins-ugly", "gstreamer", "hunspell", "hunspell-id", "hyphen", "imagemagick", "libreoffice-fresh", "pavucontrol", "qbittorrent", "simple-scan", "telegram-desktop", "thunderbird", "vlc",]
aur = [ "chromium", "discord", "handbrake", "obs-studio", "onlyoffice-bin", "ttf-ms-fonts",]

[services]
enable = []
