[meta]
name = "Designer Setup"
description = "All tools for graphic design and illustration."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "multimedia"

[packages]
install = [ "blender", "ffmpeg", "flameshot", "font-manager", "gimp", "gst-plugins-bad", "gst-plugins-good", "gst-plugins-ugly", "gstreamer", "imagemagick", "inkscape", "krita", "noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji", "pavucontrol", "vlc",]
aur = [ "darktable", "handbrake", "obs-studio", "scribus", "ttf-ms-fonts",]

[services]
enable = []
