[meta]
name = "SysAdmin Setup"
description = "Tools for system administration, DevOps, and networking."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "server"

[packages]
install = [ "aircrack-ng", "buildah", "docker", "docker-compose", "helm", "hydra", "john", "k9s", "kubectl", "minikube", "net-tools", "nmap", "podman", "remmina", "sqlmap", "tcpdump", "traceroute", "wireshark-qt",]
aur = [ "burpsuite", "lazydocker-bin",]

[services]
enable = [ "docker",]
