[meta]
name = "Programmer Setup"
description = "Ultimate environment for software engineers."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"

[packages]
install = [ "apache", "base-devel", "composer", "curl", "dbeaver", "git", "htop", "httpie", "jq", "mariadb", "mariadb-clients", "nano", "nginx", "nodejs", "npm", "openssh", "php", "php-fpm", "php-gd", "php-sqlite", "phpmyadmin", "postgresql", "redis", "sqlite", "tree", "unzip", "vim", "wget", "xdebug", "yarn", "zip",]
aur = [ "beekeeper-studio-bin", "bun-bin", "insomnia-bin", "neovim", "pnpm", "postman-bin", "visual-studio-code-bin",]

[services]
enable = [ "mariadb", "nginx", "php-fpm", "postgresql", "redis",]
