[meta]
name = "Remote Work Pack"
description = "Tools untuk meeting online dan remote desktop."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "internet"

[packages]
install = [
    "remmina"
]

aur = [
    "zoom",
    "teams",
    "anydesk-bin"
]

[services]
enable = []
