[meta]
name = "Rust Developer Pack"
description = "Paket pengembangan bahasa Rust."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "development"

[packages]
install = [
    "rustup",
    "cargo",
    "rust-analyzer"
]

aur = []

[services]
enable = []
