[meta]
name = "Science Pack"
description = "Tools komputasi dan matematika."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "education"

[packages]
install = [
    "octave",
    "scilab"
]

aur = [
    "geogebra"
]

[services]
enable = []
