[meta]
name = "Student Pack"
description = "Tools untuk menunjang aktivitas belajar siswa dan mahasiswa."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "education"

[packages]
install = [
    "libreoffice-fresh",
    "vlc",
    "firefox",
    "simple-scan",
    "gnome-calculator",
    "gnome-calendar"
]

aur = []

[services]
enable = []
