[meta]
name = "Teacher Pack"
description = "Tools untuk mendukung pengajaran dan pembuatan materi."
version = "1.0.0"
author = "TeaLinuxOS Team"
category = "education"

[packages]
install = [
    "libreoffice-fresh",
    "obs-studio",
    "poppler",
    "evince"
]

aur = [
    "zoom"
]

[services]
enable = []
